[package]
name = "tombi-text"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
tower-lsp = { workspace = true, optional = true }
tracing.workspace = true
unicode-segmentation.workspace = true
wasm-bindgen = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions.workspace = true
rstest.workspace = true

[features]
default = ["lsp", "serde"]
lsp = ["dep:tower-lsp"]
serde = ["dep:serde"]
wasm = ["dep:wasm-bindgen", "serde"]
