[package]
name = "zed-tombi"
version = "0.1.7"
authors.workspace = true
edition.workspace = true
description = "🦅  TOML Language Server  🦅 "
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
zed_extension_api.workspace = true
