# Tombi config for this project.
#
# This file is for checking if the JsonSchema is correct.
#

toml-version = "v1.0.0"

[files]
exclude = [
  "editors/intellij/src/test/testData/*",
]

[format]
[format.rules]

[lint]
[lint.rules]
key-empty = "warn"

[lsp]
code-action.enabled = true

[schema]
enabled = true
catalog = {
  paths = [
    "tombi://www.schemastore.org/api/json/catalog.json",
    "https://www.schemastore.org/api/json/catalog.json",
  ],
}

[[schemas]]
path = "schemas/type-test.schema.json"
include = ["type-test.toml"]

[[schemas]]
path = "tombi://www.schemastore.org/tombi.json"
include = [".tombi.toml", "tombi.toml", "tombi/config.toml"]
overrides = [{ targets = [""] }]

[extensions]
"tombi-toml/cargo" = {
  lsp = {
    code-action = {
      add-to-workspace-and-inherit-dependency.enabled = true,
      convert-dependency-to-table-format.enabled = true,
      inherit-dependency-from-workspace.enabled = true,
      inherit-from-workspace.enabled = true,
    },
    completion = {
      dependency-feature.enabled = true,
      dependency-version.enabled = true,
      path.enabled = true,
    },
    document-link = {
      cargo-toml.enabled = true,
      crates-io.enabled = true,
      git.enabled = true,
      path.enabled = true,
      workspace.enabled = true,
    },
    goto-declaration = {
      dependency.enabled = true,
      member.enabled = true,
      path.enabled = true,
    },
    goto-definition = {
      dependency.enabled = true,
      member.enabled = true,
      path.enabled = true,
    },
    hover = {
      dependency-detail.enabled = true,
    },
    inlay-hint = {
      default-features.enabled = true,
      dependency-version.enabled = true,
      workspace-value.enabled = true,
    },
  }
}
"tombi-toml/pyproject" = {
  lsp = {
    code-action = {
      add-to-workspace-and-use-workspace-dependency.enabled = true,
      use-workspace-dependency.enabled = true,
    },
    completion = {
      path.enabled = true,
    },
    document-link = {
      pypi-org.enabled = true,
      pyproject-toml.enabled = true,
    },
    goto-declaration = {
      dependency.enabled = true,
      member.enabled = true,
      path.enabled = true,
    },
    goto-definition = {
      dependency.enabled = true,
      member.enabled = true,
      path.enabled = true,
    },
    hover = {
      dependency-detail.enabled = true,
    },
    inlay-hint = {
      dependency-version.enabled = true,
    },
  }
}
"tombi-toml/tombi" = {
  lsp = {
    completion = {
      path.enabled = true,
    },
    document-link = {
      path.enabled = true,
    },
    goto-definition = {
      path.enabled = true,
    },
    hover.enabled = true,
  }
}
