local-date = 2025-01-30
local-date-time = 2025-01-30T23:57:55.453
offset-date-time = 2025-01-30T23:58:05.683+09:00
local-time = 23:58:14.588
array = [
  "",  # tombi: lint.rules.string-pattern = "off"
]
integer = 42
boolean = true
object = { boolean = true }
