[package]
name = "tombi-json-syntax"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tombi-rg-tree.workspace = true
