[package]
name = "tombi-lsp"
version.workspace = true  # Inherit workspace version for `tombi lsp` version log
authors.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata.cargo-shear]
ignored = ["semver"]

[dependencies]
ahash.workspace = true
chrono.workspace = true
clap = { workspace = true, optional = true }
futures.workspace = true
indexmap.workspace = true
itertools.workspace = true
regex.workspace = true
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
serde_tombi.workspace = true
tokio = { workspace = true, features = ["fs", "io-std", "rt-multi-thread"] }
tombi-ast.workspace = true
tombi-cache.workspace = true
tombi-comment-directive.workspace = true
tombi-comment-directive-store.workspace = true
tombi-config.workspace = true
tombi-date-time.workspace = true
tombi-diagnostic.workspace = true
tombi-document-tree.workspace = true
tombi-extension.workspace = true
tombi-extension-cargo.workspace = true
tombi-extension-tombi.workspace = true
tombi-extension-uv.workspace = true
tombi-formatter.workspace = true
tombi-future.workspace = true
tombi-glob.workspace = true
tombi-json.workspace = true
tombi-linter.workspace = true
tombi-parser.workspace = true
tombi-rg-tree.workspace = true
tombi-schema-store = { workspace = true, features = ["document-tree"] }
tombi-syntax.workspace = true
tombi-text = { workspace = true, features = ["lsp"] }
tombi-uri.workspace = true
tombi-validator.workspace = true
tombi-x-keyword.workspace = true
tower-lsp.workspace = true
tracing.workspace = true
unicode-segmentation.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
rstest.workspace = true
tempfile.workspace = true
textwrap.workspace = true
tokio = { workspace = true, features = ["fs", "macros", "rt"] }
tombi-test-lib.workspace = true

[features]
default = ["clap", "native"]
clap = ["dep:clap"]
native = ["tombi-schema-store/native"]
wasm = ["tombi-schema-store/wasm"]
