[package]
name = "serde_tombi"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "A TOML serialization file format using Tombi."
repository.workspace = true
license.workspace = true

[package.metadata.cargo-shear]
ignored = ["textwrap"]  # Used in `toml_text_assert_eq` macro

[dependencies]
chrono.workspace = true
dirs.workspace = true
indexmap.workspace = true
itertools.workspace = true
serde.workspace = true
textwrap.workspace = true
thiserror.workspace = true
tokio.workspace = true
tombi-ast.workspace = true
tombi-config.workspace = true
tombi-date-time.workspace = true
tombi-document.workspace = true
tombi-document-tree.workspace = true
tombi-formatter.workspace = true
tombi-parser.workspace = true
tombi-schema-store.workspace = true
tombi-toml-text.workspace = true
tombi-toml-version.workspace = true
tombi-uri.workspace = true
tracing.workspace = true
typed-builder.workspace = true
url.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
tokio = { workspace = true, features = ["macros"] }
tombi-test-lib.workspace = true

[features]
default = ["native"]
native = ["tokio/rt-multi-thread"]
wasm = []
