languageServer.presentableName = Tombi

configurations.displayName = Tombi
configurations.executable.label = Executable:
configurations.executable.placeholder = Automatic

notification.languageServerUnavailable.title = Tombi language server is unavailable
notification.languageServerUnavailable.content = Failed to find or download the Tombi language server.
