languageServer.presentableName = Tombi

configurations.displayName = Tombi
configurations.executable.label = Executable:
configurations.executable.placeholder = Automatic

notification.group.name = Tombi
notification.languageServerUnavailable.title = Tombi language server is unavailable
notification.languageServerUnavailable.content = Failed to find or download the Tombi language server.

progress.resolvingLanguageServer = Resolving Tombi language server
progress.checkingForUpdate = Checking for the latest Tombi release
progress.downloading = Downloading Tombi {0}
