[package]
name = "tombi-validator"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
addr.workspace = true
ahash.workspace = true
email_address.workspace = true
itertools.workspace = true
regex.workspace = true
serde.workspace = true
thiserror.workspace = true
tombi-ast.workspace = true
tombi-comment-directive.workspace = true
tombi-diagnostic.workspace = true
tombi-document.workspace = true
tombi-document-tree.workspace = true
tombi-future.workspace = true
tombi-json.workspace = true
tombi-parser.workspace = true
tombi-schema-store.workspace = true
tombi-syntax.workspace = true
tombi-text.workspace = true
tombi-toml-text.workspace = true
tombi-uri.workspace = true
tombi-x-keyword.workspace = true
tracing.workspace = true
uuid.workspace = true
