[package]
name = "tombi-validator"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
addr.workspace = true
ahash.workspace = true
email_address.workspace = true
itertools.workspace = true
regex.workspace = true
thiserror.workspace = true
tombi-diagnostic.workspace = true
tombi-document-tree.workspace = true
tombi-future.workspace = true
tombi-schema-store.workspace = true
tombi-text.workspace = true
tombi-x-keyword.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true
