[package]
name = "tombi-version-sort"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
itertools.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
