name: CI IntelliJ Plugin

on:
  push:
    branches:
      - main
    paths:
      - editors/intellij/**
      - .github/workflows/ci_intellij_plugin.yml
  pull_request:
    branches:
      - main
    paths:
      - editors/intellij/**
      - .github/workflows/ci_intellij_plugin.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-intellij-plugin:
    name: Build IntelliJ Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build plugin
        working-directory: ./editors/intellij
        run: |
          ./gradlew buildPlugin
      - name: Prepare plugin artifact
        id: artifact
        shell: bash
        working-directory: ./editors/intellij
        run: |
          cd build/distributions
          FILENAME=`ls *.zip`
          unzip "$FILENAME" -d content

          echo "filename=${FILENAME:0:-4}" >> $GITHUB_OUTPUT
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.filename }}
          path: ./editors/intellij/build/distributions/content/*/*

  test-intellij-plugin:
    name: Test IntelliJ Plugin
    needs: [build-intellij-plugin]
    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true
      - name: Set up Tombi
        uses: tombi-toml/setup-tombi@v1
      - name: Run tests
        working-directory: ./editors/intellij
        run: |
          ./gradlew check
      - name: Upload result
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: tests-result
          path: ${{ github.workspace }}/editors/intellij/build/reports/tests

  inspect-intellij-plugin:
    name: Inspect IntelliJ Plugin
    runs-on: ubuntu-latest

    permissions:
      contents: write
      checks: write
      pull-requests: write

    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false
      - name: Fetch sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Run Qodana
        uses: JetBrains/qodana-action@v2025.2
        with:
          args: --project-dir,editors/intellij
          cache-default-branch-only: true

  verify-intellij-plugin:
    name: Verify IntelliJ Plugin
    needs: [build-intellij-plugin]
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true
      - name: Run verifier
        continue-on-error: true
        working-directory: ./editors/intellij
        run: |
          ./gradlew verifyPlugin
      - name: Upload result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pluginVerifier-result
          path: ${{ github.workspace }}/editors/intellij/build/reports/pluginVerifier

  nightly-intellij-plugin:
    name: Publish nightly version
    if: github.event_name != 'pull_request'
    needs: [build-intellij-plugin, test-intellij-plugin, verify-intellij-plugin]
    runs-on: ubuntu-latest
    environment: IntelliJ
    continue-on-error: true

    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true
      - name: Publish plugin to Nightly channel
        env:
          PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
          CERTIFICATE_CHAIN: ${{ secrets.INTELLIJ_CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.INTELLIJ_PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.INTELLIJ_PRIVATE_KEY_PASSWORD }}
        working-directory: ./editors/intellij
        run: |
          sed -i -E \
            "s/(pluginVersion = [^[:space:]]+)/\\1-nightly.$(git rev-parse --short HEAD)/g" \
            gradle.properties

          NIGHTLY_VERSION=$(grep -oP '^pluginVersion = \K\S+' gradle.properties)

          ./gradlew publishPlugin -Pchannel=Nightly -PpluginVersion=${NIGHTLY_VERSION}

  success-intellij-plugin:
    name: Success IntelliJ Plugin
    needs:
      - build-intellij-plugin
      - test-intellij-plugin
      - inspect-intellij-plugin
      - verify-intellij-plugin
    runs-on: ubuntu-latest
    steps:
      - run: echo "success"
