name: CI IntelliJ Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - editors/intellij/**
      - .github/workflows/ci_intellij_plugin.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Export properties
        id: properties
        shell: bash
        working-directory: ./editors/intellij
        run: |
          chmod +x ./gradlew
          PROPERTIES="$(./gradlew properties --console=plain -q)"
      - name: Build plugin
        working-directory: ./editors/intellij
        run: |
          ./gradlew buildPlugin
      - name: Prepare plugin artifact
        id: artifact
        shell: bash
        working-directory: ./editors/intellij
        run: |
          cd build/distributions
          FILENAME=`ls *.zip`
          unzip "$FILENAME" -d content

          echo "filename=${FILENAME:0:-4}" >> $GITHUB_OUTPUT
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.filename }}
          path: ./editors/intellij/build/distributions/content/*/*

  test:
    name: Test
    needs: [build]
    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true
      - name: Set up Tombi
        uses: tombi-toml/setup-tombi@v1
      - name: Run tests
        working-directory: ./editors/intellij
        run: |
          chmod +x ./gradlew
          ./gradlew check
      - name: Upload result
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: tests-result
          path: ${{ github.workspace }}/editors/intellij/build/reports/tests

  inspect:
    name: Inspect
    runs-on: ubuntu-latest

    permissions:
      contents: write
      checks: write
      pull-requests: write

    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false
      - name: Fetch sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Run Qodana
        uses: JetBrains/qodana-action@v2025.1
        with:
          args: --project-dir,editors/intellij
          cache-default-branch-only: true

  verify:
    name: Verify
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true
      - name: Run verifier
        continue-on-error: true
        working-directory: ./editors/intellij
        run: |
          chmod +x ./gradlew
          ./gradlew verifyPlugin
      - name: Upload result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pluginVerifier-result
          path: ${{ github.workspace }}/editors/intellij/build/reports/pluginVerifier
