name: CI Nix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      relevant: ${{ steps.filter.outputs.relevant }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 1
      - id: filter
        uses: ./.github/actions/relevant-changes
        with:
          base-sha: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
          head-sha: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          paths: |
            .cargo/**
            .github/actions/relevant-changes/**
            Cargo.toml
            Cargo.lock
            rust-toolchain.toml
            flake.nix
            flake.lock
            crates/**
            extensions/**
            rust/**
            editors/zed/**
            toml-test/**
            xtask/**
            *.json
            .github/workflows/ci_nix.yml

  nix-build:
    needs: detect-changes
    if: needs.detect-changes.outputs.relevant == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Check flake
        run: nix flake check --print-build-logs

      - name: Build package
        run: nix build --print-build-logs
