name: CI Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUSTUP_MAX_RETRIES: 10
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  ci-rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - uses: taiki-e/install-action@nextest
    - name: Build
      run: cargo build --verbose --locked
    - name: Run tests
      run: cargo nextest run --verbose --locked

  cargo-shear:
    name: "cargo shear"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: cargo-bins/cargo-binstall@v1.14.1
      - run: cargo binstall --no-confirm cargo-shear
      - run: cargo shear
