name: Release IntelliJ plugin

on:
  workflow_dispatch:

jobs:
  publish-intellij-plugin:
    runs-on: ubuntu-latest
    environment: IntelliJ

    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true
      - name: Publish plugin to Marketplace
        env:
          PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PUBLISH_TOKEN }}
          CERTIFICATE_CHAIN: ${{ secrets.INTELLIJ_CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.INTELLIJ_PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.INTELLIJ_PRIVATE_KEY_PASSWORD }}
        working-directory: ./editors/intellij
        run: |
          chmod +x ./gradlew
          ./gradlew publishPlugin
